name: Flutter Web GitHub Pages

on:
  push:
    branches:
      - feature/manual-pos-entry

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release --base-href "/comandas_pos/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
